name: Test, build and push to github packages
on:
  pull_request:
    branches:
      - 'master'
      - 'devel'
  push:
    branches:
      - '*'
    tags:
      - '*.*.*'

jobs:
  build-images:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set ENV for branch master/main
        if: ${{ github.ref == 'refs/heads/master' }}
        run: echo "RELEASE_VERSION=latest" >> $GITHUB_ENV
      - name: Set ENV for tags
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set ENV for specific branch
        if: ${{ startsWith(github.ref, 'refs/heads/') && !endsWith(github.ref, '/master') }}
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}-${GITHUB_SHA}" >> $GITHUB_ENV
      - name: Login to ghio
        uses: docker/login-action@v1
        with:
          registry: ghcr.io 
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-kwkhtmltopdf
        uses: docker/metadata-action@v5.0.0
        with:
          images: |
            ghcr.io/camptocamp/kwkhtmltopdf

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build + Push kwkhtmltopdf
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-kwkhtmltopdf.outputs.tags }}
          labels: ${{ steps.meta-kwkhtmltopdf.outputs.labels }}

